### ISSUE TITLE
Add: Create a queue system on music command

### ISSUE THREAD

**Issue by mdxabu** [copper-dc/copper#4]
- [x] If anyone uses `/play` command while playing music, It'll add the song will be added to the queue and play next. 
- [x] Can able to play next song by button.

**Comment by mdxabu** [comment]
This feature was achieved by @m4-rk 👏

**Comment by m4-rk** [comment]
@mdxabu, What can we do next? When will you proceed the bounty💎 for me?

**Comment by mdxabu** [comment]
> @mdxabu, What can we do next? When will you proceed the bounty💎 for me?

You will receive your bounty by tomorrow itself 😀
