### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by messybrainy** [copper-dc/Copper#5]
line 617, in login
    raise TypeError(f'expected token to be a str, received {token.__class__.__name__} instead')
TypeError: expected token to be a str, received NoneType instead

this the error i am facing

**Comment by mdxabu** [comment]
Can you explain it  more correctly?

**Comment by mdxabu** [comment]
@messybrainy, Now Check the `.env.example` and rename to `.env` and provide your discord token on the env file and MongoDB connection too.

**Comment by m4-rk** [comment]
@messybrainy feel free to made a PR
